### ISSUE TITLE
Add optimizations (as a setting)

### ISSUE THREAD

**Issue by TheThirdOne** [fatiherikli/brainfuck-visualizer#25]
For longer programs, it can be tedious to run through code even at the fastest setting. Additionally, stepping through 10 plus's to debug something you actually care about is tedious.  

Possible optimizations:
- lump together +'s, -'s, <'s, >'s
- `[-]` sets the cell as zero
- `[->+<]` adds one cells value to another

This probably shouldn't be enabled by default. There could be a checkbox or have the fastest speed on the slider use it.

If you would be open to a PR, i would be happy to do it.

**Comment by fatiherikli** [comment]
It would be nice to see these optimizations with visualizations. I'm waiting your pull request :')

Thanks :+1:

**Comment by Tyilo** [comment]
Related: http://www.wilfred.me.uk/blog/2015/08/29/an-optimising-bf-compiler/
