### ISSUE TITLE
Demo website (as of a week ago) no longer works and shows 404 github pages error

### ISSUE THREAD

**Issue by Nerketur** [fatiherikli/brainfuck-visualizer#41]
The page is still on the web archive, but when going directly to it from the link in readme.md, there is only an error page.

I'm not sure why that is, but its fairly recent

**Comment by simon816** [comment]
Seems that the repository has moved. This link works: https://otomat-hackathon.github.io/brainfuck-visualizer/

**Comment by Nerketur** [comment]
and its back at the original link now.

something tells me this was a thing that happened for a october/november hackathon

in any case, the issue is resolved for now. :)
