### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by blacklistisnotracist** [fatiherikli/brainfuck-visualizer#47]
brain"fuck" can be offensive for some people. We might need to rename it something like `brainofudge-visualizer` before someone gets fucked and go viral on the social media

**Comment by shayakbanerjee99** [comment]
It isn't really targetting any communities. And also, Brainfuck was the name given to the language by it's author. If we change the name, it takes away the identity of the project. People in the past have known this esoteric programming language as Brainfuck and not something else, it is its identity and we shouldn't take it away like this.

**Comment by rdebath** [comment]
@blacklistisnotracist 
The language is over 21 it can be whatever it wants to be so you can stop being discriminatory.

**Comment by blacklistisnotracist** [comment]
Rating as NC-17 sounds good!!!
